version: '3.9'

services:
  postgres:
    container_name: dev_postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: dev_redis
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    container_name: dev_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

volumes:
  postgres_data: